package com.misiontic.unal.securityBackend.services;

/*
 * Copyright: Copyright (c) 2022
 *
 * License
 *
 * Copyright (c) 2022 by Carlos Andres Sierra Virgüez.
 * All rights reserved.
 *
 * This file is part of Academic #MisionTIC2022 Project Software.
 *
 * Academic #MisionTIC2022 Project is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * Academic #MisionTIC2022 Project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Academic #MisionTIC2022 Project.
 * If not, see <https://www.gnu.org/licenses/>.
 */

import com.misiontic.unal.securityBackend.models.Permission;
import com.misiontic.unal.securityBackend.models.Rol;
import com.misiontic.unal.securityBackend.repositories.PermissionRepository;
import com.misiontic.unal.securityBackend.repositories.RolRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.Optional;
import java.util.Set;

@Service
public class RolServices {
    // Connect services with repository methods
    @Autowired
    private RolRepository rolRepository;
    @Autowired
    private PermissionRepository permissionRepository;

    /**
     * This method returns a list of all the roles persisted in the application
     * @return rol list
     */
    public List<Rol> index(){
        return (List<Rol>)this.rolRepository.findAll();
    }

    /**
     * This method returns the information of a specific rol based on its id.
     * @param id rol id
     * @return rol information
     */
    public Optional<Rol> show(int id){
        Optional<Rol> result = this.rolRepository.findById(id);
        if(result.isEmpty())
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Requested rol does not exist in the database.");
        return result;
    }

    /**
     * This method represents the behavior of the addition of a new rol to the application.
     * Rol needs as mandatory the fields described as follows: name.
     * @param newRol new rol information
     * @return rol information after persisted in database
     */
    public ResponseEntity<Rol> create(Rol newRol){
        // Check id for new rol, it is recommended to be autogenerated
        if(newRol.getIdRol() != null) {
            Optional<Rol> result = this.rolRepository.findById(newRol.getIdRol());
            if (result.isPresent())
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                        "An existing id is provided. Please, remove from request.");
        }

        // Check mandatory fields
        if(newRol.getName() != null) {
            // Check unique fields
            Optional<Rol> tempRol = this.rolRepository.findByName(newRol.getName());
            if (tempRol.isPresent())
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                        "Name is already in the database");
            // Save if all the checks ran fine
            return new ResponseEntity<>(this.rolRepository.save(newRol), HttpStatus.ACCEPTED);
        }
       else
           throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                   "Mandatory fields have not been provided.");
    }

    /**
     * This method represents the behavior of an update of rol information
     * @param id rol id
     * @param updatedRol rol information to update
     * @return updated rol
     */
    public ResponseEntity<Rol> update(int id, Rol updatedRol){
        if(id > 0){
            Optional<Rol> tempRol = this.show(id);
            if(tempRol.isPresent()){
                if(updatedRol.getName() != null)
                    tempRol.get().setName(updatedRol.getName());
                if(updatedRol.getDescription() != null)
                    tempRol.get().setDescription(updatedRol.getDescription());
                try {
                    // If any database constraint is violated it is going to launch an error
                    return new ResponseEntity<>(this.rolRepository.save(tempRol.get()), HttpStatus.CREATED);
                }
                catch(Exception ex){
                    throw new ResponseStatusException(HttpStatus.CONFLICT,
                            "Database is getting a conflict by a constraint.");
                }
            }
            else
                throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Requested rol does not exist in the database.");
        }
        else
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Rol ID cannot be negative.");
    }

    /**
     * This method represents the behavior of the addition of a permission to the current rol
     * @param idRol rol id
     * @param idPermission permission id to add
     * @return updated rol
     */
    public ResponseEntity<Rol> addPermission(int idRol, int idPermission) {
        Optional<Rol> rol = this.rolRepository.findById(idRol);
        // Check if rol exists in database
        if(rol.isPresent()) {
            Optional<Permission> permission = this.permissionRepository.findById(idPermission);
            // Check if permission exists in database
            if (permission.isPresent()) {
                Set<Permission> tempPermissions = rol.get().getPermissions();
                if(tempPermissions.contains(permission))
                    throw new ResponseStatusException(HttpStatus.CONFLICT,
                            "Rol already has the permission.");
                tempPermissions.add(permission.get());
                rol.get().setPermissions(tempPermissions);
                return new ResponseEntity<>(this.rolRepository.save(rol.get()), HttpStatus.CREATED);
            }
            else
                throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Provided permission does not exist in the database.");
        }
        else
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Provided rol does not exist in the database.");
    }

    /**
     * This method represents the behavior of the removing of a permission to the current rol
     * @param idRol rol id
     * @param idPermission permission id to remove
     * @return updated rol
     */
    public ResponseEntity<Rol> removePermission(int idRol, int idPermission) {
        Optional<Rol> rol = this.rolRepository.findById(idRol);
        // Check if rol exists in database
        if(rol.isPresent()) {
            Optional<Permission> permission = this.permissionRepository.findById(idPermission);
            // Check if permission exists in database
            if (permission.isPresent()) {
                Set<Permission> tempPermissions = rol.get().getPermissions();
                if(!tempPermissions.contains(permission))
                    throw new ResponseStatusException(HttpStatus.CONFLICT,
                            "Rol does not have the permission.");
                tempPermissions.remove(permission.get());
                rol.get().setPermissions(tempPermissions);
                return new ResponseEntity<>(this.rolRepository.save(rol.get()), HttpStatus.CREATED);
            }
            else
                throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Provided permission does not exist in the database.");
        }
        else
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                    "Provided rol does not exist in the database.");
    }

    /**
     * This method represents the behavior of a rol deletion from the database based on its id
     * @param id user id
     * @return status in boolean
     */
    public ResponseEntity<Boolean> delete(int id){
        Boolean success = this.show(id).map(rol -> {
            this.rolRepository.delete(rol);
            return true;
        }).orElse(false);
        if(success)
            return new ResponseEntity<>(true, HttpStatus.NO_CONTENT);
        else
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "Rol cannot be deleted. Check if it exists in database.");
    }

    /**
     * This function represents the behavior of a grant validation for a rol
     * to access to a given permission
     * @param idRol rol id
     * @param permission permission id
     * @return grant status
     */
    public ResponseEntity<Boolean> validateGrant(int idRol, Permission permission){
        boolean isGrant = false;
        Optional<Rol> tempRol = this.rolRepository.findById(idRol);
        // Check if rol exists in database
        if(tempRol.isPresent()){
            // Check each rol permission vs the provided permission
            for(Permission rolPermission: tempRol.get().getPermissions())
                if(rolPermission.getUrl().equals(permission.getUrl()) &&
                        rolPermission.getMethod().equals(permission.getMethod())){
                   isGrant = true;
                   break;
                }
            if(isGrant)
                return new ResponseEntity<>(true, HttpStatus.OK);
            else
                return new ResponseEntity<>(false, HttpStatus.UNAUTHORIZED);
        }
        else
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
                "The provided rol does not exist in the database.");
    }
}
